### ISSUE TITLE
Schreibfehler in composer.json

### ISSUE THREAD

**Issue by do-while** [BugBuster1701/contao-botstatistics-bundle#1]
"languages_cto": "src/Resources/contao/anguages",

Da fehlt wohl ein "l"

**Comment by BugBuster1701** [comment]
Jo, aber da bin ich eh noch in Entwicklung (Branch feature/contao4)

**Comment by do-while** [comment]
Ich war nur auf der Suche nach einem Beispiel, da ist mir das aufgefallen.

Ich habe versucht, dass der Composer mir eine Datei ins files/ legt, wie das alte TL_FILES. Habe dazu kein Beispiel gefunden.

**Comment by BugBuster1701** [comment]
Da fallen mir einige Möglichkeiten ein, die meisten davon nicht ganz "sauber". Problem ist, dass das composer-plugin nicht arbeitet wenn die Erweiterung vom Typ "contao-bundle" ist.
Somit landet alles in vendor/.... und das war es, kein umkopieren mehr.

Rein kopieren in files/ wäre z.B. über config/runonce.php möglich. Problem: Bei einer Deinstallation bleibt das da liegen. 
Die Composer Scripte wie "post-install-cmd" sollen angeblich nur im Projekt also in der Haupt composer.json funktionieren, wie es die z.B. bei der managed-edition gibt.

Eventuell ginge das über Composer Components, sofern man das Ziel dabei angeben kann, das war mir damals nicht gelungen.

Wäre aber mal ein gutes Gesprächsthema auf dem Camp :-)
