### ISSUE TITLE
Installation unter Contao 5.3 bricht ab

### ISSUE THREAD

**Issue by Schmidty2** [BugBuster1701/contao-botstatistics-bundle#18]
Hallo,
die Installation unter Contao 5.3.1  bricht ab.
Contao 5.3.1
Provider All-Inkl
PHP 8.3.3

Wie bei https://github.com/BugBuster1701/contao-visitors-bundle/issues/162#issue-2176612683 ebenfalls ein Problem mit monolog.

>   Problem 1
>     - symfony/http-kernel[v4.4.0, ..., v4.4.8] require php ^7.1.3 -> your php version (8.3.3.0) does not satisfy that requirement.
>     - monolog/monolog[2.0.0, ..., 2.0.2] require php ^7.2 -> your php version (8.3.3.0) does not satisfy that requirement.
>     - contao/core-bundle[4.9.0, ..., 4.10.4] require php ^7.2 -> your php version (8.3.3.0) does not satisfy that requirement.
>     - numero2/contao-proper-filenames[v2.1.0, ..., v2.1.6] require contao/core-bundle ^4.4.0 -> satisfiable by contao/core-bundle[4.4.0, ..., 4.13.38].
>     - contao/core-bundle[4.13.0, ..., 4.13.38] require symfony/http-kernel ^5.4 -> satisfiable by symfony/http-kernel[v5.4.0, ..., v5.4.37].
>     - contao/core-bundle[4.12.0, ..., 4.12.7] require symfony/http-kernel ^4.4 || ^5.2 -> satisfiable by symfony/http-kernel[v4.4.0, ..., v4.4.51, v5.2.0, ..., v5.4.37].
>     - contao/core-bundle[4.11.0, ..., 4.11.9] require symfony/http-kernel 4.4.* || 5.2.* -> satisfiable by symfony/http-kernel[v4.4.0, ..., v4.4.51, v5.2.0, ..., v5.2.14].
>     - contao/core-bundle[4.9.10, ..., 4.10.7] require symfony/http-kernel 4.4.* -> satisfiable by symfony/http-kernel[v4.4.0, ..., v4.4.51].
>     - You can only install one version of a package, so only one of these can be installed: symfony/http-kernel[v2.1.0, ..., v2.8.52, v3.0.0, ..., v3.4.49, v4.0.0, ..., v4.4.51, v5.0.0, ..., v5.4.37, v6.0.0, ..., v6.4.5, v7.0.0, ..., v7.0.5].
>     - contao/core-bundle 4.4.0 requires terminal42/header-replay-bundle ^1.0 -> satisfiable by terminal42/header-replay-bundle[1.0.0, ..., 1.5.3].
>     - bugbuster/contao-botstatistics-bundle[1.1.0, ..., 1.1.1] require symfony/http-kernel ^6.4 -> satisfiable by symfony/http-kernel[v6.4.0, ..., v6.4.5].
>     - terminal42/header-replay-bundle[1.0.0, ..., 1.4.4] require php >=5.6,<8 -> your php version (8.3.3.0) does not satisfy that requirement.
>     - terminal42/header-replay-bundle[1.5.0, ..., 1.5.3] require php ^5.6 | ^7.0 -> your php version (8.3.3.0) does not satisfy that requirement.
>     - contao/core-bundle[4.4.1, ..., 4.4.17] require php ^5.6|^7.0 -> your php version (8.3.3.0) does not satisfy that requirement.
>     - contao/core-bundle[4.4.18, ..., 4.4.57] require php ^5.6 || ^7.0 -> your php version (8.3.3.0) does not satisfy that requirement.
>     - contao/core-bundle[4.5.0, ..., 4.8.8] require php ^7.1 -> your php version (8.3.3.0) does not satisfy that requirement.
>     - Root composer.json requires bugbuster/contao-botstatistics-bundle ^1.1 -> satisfiable by bugbuster/contao-botstatistics-bundle[1.1.0, 1.1.1].
>     - Root composer.json requires numero2/contao-proper-filenames ^2.1 -> satisfiable by numero2/contao-proper-filenames[v2.1.0, ..., v2.1.8].
>     - numero2/contao-proper-filenames[v2.1.7, ..., v2.1.8] require contao/core-bundle ^4.9 || ^5.0 -> satisfiable by contao/core-bundle[4.9.0, ..., 4.13.38, 5.0.0, ..., 5.3.1].
>     - contao/core-bundle[5.0.0, ..., 5.3.1] require monolog/monolog ^2.0 -> satisfiable by monolog/monolog[2.0.0, ..., 2.9.2].
>     - You can only install one version of a package, so only one of these can be installed: monolog/monolog[1.11.0, ..., 1.27.1, 2.0.0, ..., 2.9.2, 3.0.0, ..., 3.5.0].
>     - Conclusion: install monolog/monolog 3.5.0 (conflict analysis result)

**Comment by BugBuster1701** [comment]
Versuche mal die neue Version 1.1.2 zu installieren.

**Comment by Schmidty2** [comment]
Ich habe gerade in einer neuen, ertra für die Tests installierten Contao-Installation versucht, die Version 1.1.2 zu installieren.
Leider ohne Erfolg.
All-Inkl Premium-Paket
PHP 8.3.3
ContaoManager 1.8.4
Contao 5.3.1, keine weiteren Erweiterungen installiert


> $ /bin/php83 -q -dmax_execution_time=0 -dmemory_limit=-1 -ddisplay_errors=0 -ddisplay_startup_errors=0 -derror_reporting=0 -dallow_url_fopen=1 -ddisable_functions= -ddate.timezone=Europe/Berlin /www/htdocs/w1234567/verzeichnisname/public/contao-manager.phar.php composer require bugbuster/contao-botstatistics-bundle --no-update --no-scripts --prefer-stable --sort-packages --no-ansi --no-interaction
> 
> 
> Using version ^1.1 for bugbuster/contao-botstatistics-bundle
> /www/htdocs/w1234567/verzeichnisname/composer.json has been updated
> 
> Process terminated with exit code 0
> Result: OK
> 
> Resolving dependencies using Composer Cloud v3.7.0
> 
> [6.8MiB/0.26s] Loading composer repositories with package information
> [64.3MiB/11.11s] Updating dependencies
> [122.2MiB/11.98s] Your requirements could not be resolved to an installable set of packages.
> [122.2MiB/11.98s] 
>   Problem 1
>     - Conclusion: don't install bugbuster/contao-botstatistics-bundle 1.1.2 (conflict analysis result)
>     - monolog/monolog[2.0.0, ..., 2.0.2] require php ^7.2 -> your php version (8.3.3.0) does not satisfy that requirement.
>     - bugbuster/contao-botstatistics-bundle[1.1.0, ..., 1.1.1] require contao/core-bundle ^5.2 -> satisfiable by contao/core-bundle[5.2.0, ..., 5.3.1].
>     - contao/core-bundle[5.2.0, ..., 5.3.0] require monolog/monolog ^2.0 -> satisfiable by monolog/monolog[2.0.0, ..., 2.9.2].
>     - You can only install one version of a package, so only one of these can be installed: monolog/monolog[1.11.0, ..., 1.27.1, 2.0.0, ..., 2.9.2, 3.0.0, ..., 3.5.0].
>     - Conclusion: don't install one of monolog/monolog[3.5.0], contao/core-bundle[5.3.1] (conflict analysis result)
>     - Conclusion: don't install bugbuster/contao-botdetection-bundle[1.9.2] | install monolog/monolog[3.5.0] (conflict analysis result)
>     - bugbuster/contao-botstatistics-bundle[1.1.0, ..., 1.1.1] require bugbuster/contao-botdetection-bundle ^1.9 -> satisfiable by bugbuster/contao-botdetection-bundle[1.9.0, 1.9.1, 1.9.2].
>     - Root composer.json requires bugbuster/contao-botstatistics-bundle ^1.1 -> satisfiable by bugbuster/contao-botstatistics-bundle[1.1.0, 1.1.1, 1.1.2].
> 
> Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.
> [122.2MiB/11.98s] Running update with --no-dev does not mean require-dev is ignored, it just means the packages will not be installed. If dev requirements are blocking the update you have to resolve those problems.
> [38.9MiB/12.06s] Memory usage: 38.86MB (peak: 162.75MB), time: 12.07s.
> [38.9MiB/12.06s] Finished Composer Cloud resolving.
> 
> Cloud Job ID KD7Cfq20D09lWSuFe2Nbzu02zDO3LTS3oY8F9oYiEeKeoKECUj87FHeDqGHHCaHSd91QOIPSNMO3kamFOLrttd9D9 failed



Hier noch die composer.json:

```
{
    "type": "project",
    "require": {
        "contao/conflicts": "*@dev",
        "contao/manager-bundle": "5.3.*",
        "contao/calendar-bundle": "5.3.*",
        "contao/comments-bundle": "5.3.*",
        "contao/faq-bundle": "5.3.*",
        "contao/listing-bundle": "5.3.*",
        "contao/news-bundle": "5.3.*",
        "contao/newsletter-bundle": "5.3.*"
    },
    "extra": {
        "public-dir": "public",
        "contao-component-dir": "assets"
    },
    "scripts": {
        "post-install-cmd": [
            "@php vendor/bin/contao-setup"
        ],
        "post-update-cmd": [
            "@php vendor/bin/contao-setup"
        ]
    }
}
```

**Comment by BugBuster1701** [comment]
Bei mir läuft diese Installation ohne Probleme. (allerdings unter PHP 8.2)
Die Version 1.1.2 fordert monolog in Version 2.9 oder höher an, bei dir wird aber:
`monolog/monolog[2.0.0, ..., 2.0.2]` versucht zu installieren, was nicht geht wegen PHP 7.2.

Ich vermute es liegt an PHP 8.3. 
Denn Monolog gibt es für PHP 8.3 erst ab Version 3.5.0 und das ist wieder inkompatible mit dem Rest.
Hast du eine Chance auf PHP 8.2 zurück zugehen?

**Comment by Schmidty2** [comment]
Ich probiere morgen die Installation mit PHP 8.2.
Wollte die neue Seite gleich mit der neuesten PHP-Version aufbauen, was wohl aus besagtem Grund nicht möglich ist.

**Comment by Schmidty2** [comment]
Hallo,
mit PHP 8.2 lässt sich die Installation problemlos durchführen (bei allen Paketen), es ist also ein Problem mit PHP 8.3.

**Comment by BugBuster1701** [comment]
Ja, das Problem konnte ich eingrenzen, ich muss nur noch raus bekommen, wie ich es löse, da es nicht ein Teil meiner eigenen Programmierung betrifft.
