### ISSUE TITLE
Anzeige im Backend abgeschnitten

### ISSUE THREAD

**Issue by akroii** [BugBuster1701/contao-botstatistics-bundle#3]
Im Contao Backend wird im Reiter Botstatistik die Anzeige abgeschnitten:

<img width="848" alt="bildschirmfoto 2018-03-16 um 17 27 48" src="https://user-images.githubusercontent.com/8830861/37532757-36914856-2940-11e8-9a64-8e13edf2e3f5.png">

Botstatistik Modul 1.0.3
Contao 4.4.14

**Comment by BugBuster1701** [comment]
Welcher Browser? Ist bei mir nur minimal, daher nicht aufgefallen bisher.

**Comment by BugBuster1701** [comment]
angepasst in 1.0.4
